---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: localstack-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack-app
  template:
    metadata:
      labels:
        app: localstack-app
    spec:
      serviceAccountName: localstack-scc
      containers:
        - name: localstack
          image: public.ecr.aws/localstack/localstack
          ports:
            - name: http
              containerPort: 4566
              protocol: TCP
          # resources:
          #   requests:
          #     memory: "200Mi"
          #     cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: localstack-app
spec:
  ports:
    - name: http-4566
      port: 4566
      protocol: TCP
      targetPort: 4566
  selector:
    app: localstack-app
