apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-anyuid-scc
subjects:
- kind: ServiceAccount
  name: devspaces-scc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scc-anyuid-role
